"""Constants sharable between internal plugin python modules."""

from __future__ import absolute_import, division, print_function, unicode_literals

# Candidates for FMEObjects external usage (pyfme.py)
FME_SUCCESS = 0
FME_FAILURE = 1
FME_TRUE = 1
FME_FALSE = 0

# Internal constants to share between plugins
END_OF_FILE = None

kFME_UTF8 = "utf-8"
kFME_UTF16 = "utf-16"

kFME_DEBUG = "FME_DEBUG"
kFME_UNUSED = "<Unused>"

kFME_READER = "Reader"
kFME_READER_TYPE = "READER_TYPE"
kFME_READER_KEYWORD = "READER_KEYWORD"
kFME_WRITER_TYPE = "WRITER_TYPE"
kFME_WRITER_KEYWORD = "WRITER_KEYWORD"

kRETRIEVE_ALL_TABLE_NAMES = "RETRIEVE_ALL_TABLE_NAMES"
kFME_FETCH_IDS_AND_DEFS = "FETCH_IDS_AND_DEFS"
kFME_FETCH_DEFS_ONLY = "FETCH_DEFS_ONLY"
kFME_DYNAMIC_WORKFLOW = "DYNAMIC_WORKFLOW"

kFME_DEFLINE_SUFFIX = "_DEF"
kFME_READER_INHERITED_VALUE = "INHERIT_FROM_READER"
kFME_WRITER_INHERITED_VALUE = "INHERIT_FROM_WRITER"

kFME_WRITER = "Writer"
kFME_WRITER_MODE = "WRITER_MODE"
kFME_WRITER_MODE_PRE = "_WRITER_MODE"
kFME_WRITER_MODE_INHERIT = "INHERIT_FROM_WRITER"
kFME_WRITER_MODE_INSERT = "INSERT"
kFME_WRITER_MODE_UPDATE = "UPDATE"
kFME_WRITER_MODE_DELETE = "DELETE"
kFME_WRITER_MODE_LIST = [kFME_WRITER_MODE_INSERT, kFME_WRITER_MODE_UPDATE, kFME_WRITER_MODE_DELETE]
kFME_DB_OPERATION_ATTR = "fme_db_operation"
kFME_ATTRIBUTE_READING = "fme_attribute_reading"

kFME_TABLE_HANDLING_ATTR = "fme_table_handling"
kFME_FEATURE_OPERATION_ATTR = "fme_feature_operation"
kFME_SELECTION_METHOD_ATTR = "fme_selection_method"
kFME_MATCH_COLUMNS_ATTR = "fme_match_columns"
kFME_WHERE_BUILDER_CLAUSE_ATTR = "fme_where_builder_clause"
kFME_WHERE_ATTR = "fme_where"
kFME_DB_TRANSACTION_ATTR = "fme_db_transaction"

# fme_feature_operation options:
kFME_FEATURE_OPERATION_UPSERT = "UPSERT"
kFME_FEATURE_OPERATION_DELSERT = "DELSERT"
kFME_FEATURE_OPERATION_INSERT = "INSERT"
kFME_FEATURE_OPERATION_UPDATE = "UPDATE"
kFME_FEATURE_OPERATION_DELETE = "DELETE"
kFME_FEATURE_OPERATION_MULTIPLE = "MULTIPLE"
kFME_FEATURE_OPERATIONS = set(
    [
        kFME_FEATURE_OPERATION_INSERT,
        kFME_FEATURE_OPERATION_UPDATE,
        kFME_FEATURE_OPERATION_DELETE,
        kFME_FEATURE_OPERATION_MULTIPLE,
    ]
)

# fme_table_handling options:
kFME_TABLE_CREATE_IF_MISSING = "CREATE_IF_MISSING"
kFME_TABLE_DROP_CREATE = "DROP_CREATE"
kFME_TABLE_TRUNCATE_EXISTING = "TRUNCATE_EXISTING"
kFME_TABLE_USE_EXISTING = "USE_EXISTING"

kFME_TEMPLATE_FEATURE_TYPE = "fme_template_feature_type"

# Common messages (formatscommon.fms).
kFME_MSGNUM_USING_PROXY = 926850
# 926851
kFME_MSGNUM_PROXY_AUTH_MODE_UNSUPPORTED = 926852
# 926853
kFME_MSGNUM_WRITER_MODE_UNSUPPORTED = 926854
kFME_MSGNUM_READER_KEYWORD_INCORRECT_VALUE = 926855
kFME_MSGNUM_NETWORK_ERROR = 926856
kFME_MSGNUM_SSL_CERTIFICATE_VERIFY_FAILED = 926857
kFME_MSGNUM_WRITER_FEATURE_MISSING_COORDSYS = 926858
kFME_MSGNUM_WRITER_REPROJECTION_FAILED = 926859
kFME_MSGNUM_WRITER_BINARY_ATTR_UNSUPPORTED = 926867
kFME_MSGNUM_HTTP_AUTH_TYPE = 926869
kFME_MSGNUM_NAMED_CONNECTION_NOT_FOUND = 926882
kFME_MSGNUM_INTERNAL_ERROR = 926885

# Keywords for setConstraints() and getProperties().
kFME_NUM_ENTRIES = "fme_num_entries"
kFME_DIMENSION = "fme_dimension"
kFME_EXTENTS = "fme_extents"
kFME_COORDINATE_SYSTEM = "fme_coordinate_system"
kFME_FEATURE_IDENTIFIER = "fme_feature_identifier"
kFME_ALL_SCHEMAS = "fme_all_schemas"
kFME_EXECUTE_SQL = "fme_execute_sql"
kFME_SQL_STATEMENT = "fme_sql_statement"
kFME_METADATA = "fme_metadata"
kFME_MIN_X = "fme_min_x"
kFME_MIN_Y = "fme_min_y"
kFME_MAX_X = "fme_max_x"
kFME_MAX_Y = "fme_max_y"
kFME_PROP_COORDSYS_AWARE = "fme_prop_coord_sys_aware"
kFME_PROP_SPATIAL_INDEX = "fme_prop_spatial_index"

# Values considered to be 'true'. All strings lowercase.
kFME_TRUE_VALUES = frozenset(("yes", "true", "y", "t", "1", 1, True))

# --- Constant Definitions for error handling
kFME_REJECTION_CODE = "fme_rejection_code"
kFME_REJECTION_MESSAGE = "fme_rejection_message"
kFME_GENERAL_ERROR = "ERROR_DURING_PROCESSING"

# Constant for FME Names encoding keyword. Generally defined in workspace.
kFME_NAMES_ENCODING = "FME_NAMES_ENCODING"
